name: Publish Docker image

#on: [push]
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feature

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Build the Go app
        run: |
          cd D:/STUDY/TERM-6/pursovproject
          go build -o app app.go

      - name: Log in to Docker Hub
        run: docker login -u zhkerin13656 -p Karina131103

      - name: Build Docker image
        run: docker build -t my-go-app .

  #deploy:
    #runs-on: self-hosted
      - name: add Tag
        run: docker tag my-go-app zhkerin13656/my-go-app
        
    #steps:
      - name: Push Docker image 
        #run: docker push my-go-app  
        run: docker push zhkerin13656/my-go-app:latest

      - name: Deploy (run docker container)
        run: docker run -d -p 8888:8888 my-go-app
