# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Publish Docker image

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Build the Go app
        run: |
          cd D:/STUDY/TERM-6/pursovproject
          go build -o app app.go

      - name: Log in to Docker Hub
        run: docker login -u zhkerin13656 -p Karina131103

      - name: Build Docker image
        run: docker build -t my-go-app .

  deploy:
    runs-on: self-hosted

    steps:
    #  - name: Push Docker image
     #   run: docker push my-go-app

      - name: Run Docker container
        run: docker run -d -p 8888:8888 my-go-app
